#- name:  Check Jenkins connection
#  shell:  "{{JENKINS_CLI_PREFIX}} who-am-i"


- name:  Create Jenkins Job
  include_tasks:  job_creation.yml
  loop:
    -  {name: "sample1", repname: "sample1"}



#    - name:  Update Job
#      when:  check_job.rc == 0

